### ISSUE TITLE
mods/version: implement

### ISSUE THREAD

**Issue by demget** [automatica-team/plant#19]
A module that handles `/version` command that sends the bot version to the user. 

```yaml
mods:
  - import: plant/version
    repo: automatica-team/bots
```

```go
func githubTags(repo string) ([]string, error) {
	resp, err := http.Get("https://api.github.com/repos/" + repo + "/tags")
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	var tags []struct {
		Name string `json:"name"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&tags); err != nil {
		return nil, err
	}

	var names []string
	for _, tag := range tags {
		names = append(names, tag.Name)
	}

	return names, nil
}
```
