### ISSUE TITLE
mods/monitor: implement

### ISSUE THREAD

**Issue by demget** [automatica-team/plant#2]
**Config usage:**
```yml
mods:
  - import: plant/monitor
    url: $CH_URL
```

**Code example:**
```go
// func Import

mon, err := monitor.New(...)

mod.Use(mon.Middleware())
```

**Ref:**
https://github.com/go-telebot/pkg
